[package]
name = "naskah"
version = "0.1.0"
authors = ["L RMN <lrmnid@gmail.com>"]
repository = "https://github.com/lrmn7/naskah"
description = "Bahasa pemrograman dengan sintaks Bahasa Indonesia"
license = "MIT"

[workspace]

members = [
  "demo",
  "parser",
  "printer"
]

[dependencies]
